data:extend({
    {
        label = "Test kitchen 1",
        id = "base.item.kitchen_1",
        type = "item",
        category = "kitchen",
        graphics = { path = "[base]/graphics/items/test.png" },
        size = {1, 1},
        health = 100,
        cost = 42,
    },
    {
        label = "Test kitchen 2",
        id = "base.item.kitchen_2",
        type = "item",
        category = "kitchen",
        graphics = { path = "[base]/graphics/items/test.png" },
        size = {1, 1},
        health = 100,
        cost = 42,
    },
    {
        label = "Test kitchen 3",
        id = "base.item.kitchen_3",
        type = "item",
        category = "kitchen",
        graphics = { path = "[base]/graphics/items/test.png" },
        size = {1, 1},
        health = 100,
        cost = 42,
    },
    {
        label = "Test kitchen 4",
        id = "base.item.kitchen_4",
        type = "item",
        category = "kitchen",
        graphics = { path = "[base]/graphics/items/test.png" },
        size = {1, 1},
        health = 100,
        cost = 42,
    },
    {
        label = "Test power 1",
        id = "base.item.power_1",
        type = "item",
        category = "power",
        graphics = { path = "[base]/graphics/items/test.png" },
        size = {1, 1},
        health = 100,
        cost = 42,
    },
    {
        label = "Test furniture 1",
        id = "base.item.furniture_1",
        type = "item",
        category = "furniture",
        graphics = { path = "[base]/graphics/items/test.png" },
        size = {1, 1},
        health = 100,
        cost = 42,
    },
    {
        label = "Test furniture 2",
        id = "base.item.furniture_2",
        type = "item",
        category = "furniture",
        graphics = { path = "[base]/graphics/items/test.png" },
        size = {1, 1},
        health = 100,
        cost = 42,
    },
    {
        label = "Test factory 1",
        id = "base.item.factory_1",
        type = "item",
        category = "factory",
        graphics = { path = "[base]/graphics/items/test.png" },
        size = {1, 1},
        health = 100,
        cost = 42,
    },
    {
        label = "Test industrial 1",
        id = "base.item.industrial_2",
        type = "item",
        category = "industrial",
        graphics = { path = "[base]/graphics/items/test.png" },
        size = {1, 1},
        health = 100,
        cost = 42,
    },
    {
        label = "Test industrial 2",
        id = "base.item.industrial_2",
        type = "item",
        category = "industrial",
        graphics = { path = "[base]/graphics/items/test.png" },
        size = {1, 1},
        health = 100,
        cost = 42,
    },
})