data:extend({
    { label = "Bed",
        name = "base.bed",
        type = "item_group",
        category = "quarter",
        build = { cost = 100 },
        size = {1, 2},
        graphics = { path = "[base]/graphics/items/bed.png" },
        receipts = {label = "Wood", icon = "[base]/graphics/icons/material/wood.png", components = { item = "base.consumable.wood_log", quantity = 10}},
        actions = { type = "use", effects = {{type = "energy", quantity = 1}}}},
    { label = "Wood Bed",
        name = "base.bed.wood",
        type = "item",
        category = "quarter",
        build = { cost = 100 },
        size = {1, 2},
        graphics = { path = "[base]/graphics/items/bed_wood.png" },
        receipts = {label = "Wood", icon = "[base]/graphics/icons/material/wood.png", components = { item = "base.consumable.wood_log", quantity = 10}},
        actions = { type = "use", effects = {{type = "energy", quantity = 1}}}},
    { label = "Sandstone Bed",
        name = "base.bed.sandstone",
        type = "item",
        category = "quarter",
        build = { cost = 100 },
        size = {1, 2},
        graphics = { path = "[base]/graphics/items/bed_sandstone.png" },
        receipts = {label = "Sandstone", icon = "[base]/graphics/icons/material/sandstone.png", components = { item = "base.sandstone_brick", quantity = 10}},
        actions = { type = "use", effects = {{type = "energy", quantity = 1}}}},
})
