data:extend({
    {
        label = "Euglena bloom",
        id = "base.seaweed1",
        graphics = { path = "[base]/graphics/items/resources/desert_berry.png" },
        --graphics = "[base]/graphics/items/resources/seaweed1.png",
        type = "resource",
        category = "algae",
        plant = {
            oxygen = 2,
            growing = 10000,
            nourish = 2400,
            states = {
                { id = "depleted",    value = -0.1,   temperature = {-999, 999},  light = {-999, 999} },
                { id = "stasis",      value = 0,      temperature = {0, 50},      light = {0, 100} },
                { id = "partial",     value = 0.5,    temperature = {14, 50},     light = {0, 100} },
                { id = "regular",     value = 1,      temperature = {20, 50},     light = {0, 100} },
                { id = "exceptional", value = 1.25,   temperature = {25, 50},     light = {0, 100} },
            },
        },
        actions = {{
            type = "gather",
            cost = 20,
            products = {
                { item = "base.seaweed", quantity = {1, 1}, rate = 1 },
            },
        }},
    },
    {
        label = "Chlorella",
        id = "base.seaweed2",
        graphics = { path = "[base]/graphics/items/resources/seaweed2.png" },
        type = "resource",
        category = "algae",
        plant = {
            oxygen = 2,
            growing = 10000,
            nourish = 2400,
            states = {
                { id = "depleted",    value = -0.1,   temperature = {-999, 999},  light = {-999, 999} },
                { id = "stasis",      value = 0,      temperature = {0, 50},      light = {0, 100} },
                { id = "partial",     value = 0.5,    temperature = {14, 50},     light = {0, 100} },
                { id = "regular",     value = 1,      temperature = {20, 50},     light = {0, 100} },
                { id = "exceptional", value = 1.25,   temperature = {25, 50},     light = {0, 100} },
            },
        },
        actions = {{
            type = "gather",
            cost = 20,
            products = {
                { item = "base.seaweed", quantity = {1, 1}, rate = 1 },
            },
        }},
    },
    {
        label = "Eel grass",
        sciLabel = "Zostera marina",
        id = "base.seaweed3",
        --        graphics = "[base]/graphics/items/resources/seaweed3.png",
        graphics = { path = "[base]/graphics/items/resources/desert_green_plant.png" },
        --        graphics = "[base]/graphics/items/resources/desert_green_plant.png",
        type = "resource",
        category = "algae",
        size = {1, 1},
        light = { power = .5, radius = 5 },
        plant = {
            oxygen = 2,
            growing = 10000,
            nourish = 2400,
            states = {
                { id = "depleted",    value = -0.1,   temperature = {-999, 999},  light = {-999, 999} },
                { id = "stasis",      value = 0,      temperature = {0, 50},      light = {0, 100} },
                { id = "partial",     value = 0.5,    temperature = {14, 50},     light = {0, 100} },
                { id = "regular",     value = 1,      temperature = {20, 50},     light = {0, 100} },
                { id = "exceptional", value = 1.25,   temperature = {25, 50},     light = {0, 100} },
            },
        },
        actions = {{
            type = "gather",
            cost = 20,
            products = {
                { item = "base.seaweed", quantity = {1, 1}, rate = 1 },
            },
        }},
    },
    {
        label = "Green algae",
        id = "base.seaweed4",
        type = "resource",
        graphics = { path = "[base]/graphics/items/resources/seaweed4.png" },
        category = "algae",
        size = {1, 1},
        plant = {
            oxygen = 2,
            growing = 10000,
            nourish = 2400,
            states = {
                { id = "depleted",    value = -0.1,   temperature = {-999, 999},  light = {-999, 999} },
                { id = "stasis",      value = 0,      temperature = {0, 50},      light = {0, 100} },
                { id = "partial",     value = 0.5,    temperature = {14, 50},     light = {0, 100} },
                { id = "regular",     value = 1,      temperature = {20, 50},     light = {0, 100} },
                { id = "exceptional", value = 1.25,   temperature = {25, 50},     light = {0, 100} },
            },
        },
        actions = {{
            type = "gather",
            cost = 20,
            products = {
                { item = "base.seaweed", quantity = {5, 10}, rate = 1 },
            },
        }},
    },
    {
        label = "Golden brown algae",
        sciLabel = "Chrysophyceae",
        graphics = { path = "[base]/graphics/items/resources/seaweed5.png" },
        id = "base.seaweed5",
        type = "resource",
        category = "algae",
        size = {1, 1},
        plant = {
            oxygen = 2,
            growing = 10000,
            nourish = 2400,
            states = {
                { id = "depleted",    value = -0.1,   temperature = {-999, 999},  light = {-999, 999} },
                { id = "stasis",      value = 0,      temperature = {0, 50},      light = {0, 100} },
                { id = "partial",     value = 0.5,    temperature = {14, 50},     light = {0, 100} },
                { id = "regular",     value = 1,      temperature = {20, 50},     light = {0, 100} },
                { id = "exceptional", value = 1.25,   temperature = {25, 50},     light = {0, 100} },
            },
        },
        actions = {{
            type = "gather",
            cost = 20,
            products = {
                { item = "base.seaweed", quantity = {1, 1}, rate = 1 },
            },
        }},
    },
})