/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJNI1 */
 
#ifndef _Included_TestJNI1
#define _Included_TestJNI1
#ifdef __cplusplus
extern " C " {
#endif
/*
*  Class:     JNIBridge
*  Method:    onAddResource
*  Signature: ()V
*/
JNIEXPORT void JNICALL Java_JNIBridge_onAddResource(JNIEnv *, jobject);
#ifdef __cplusplus
}
#endif
#endif