package org.smallbox.faraway.client.ui.extra;

public enum Align {
    LEFT, RIGHT, CENTER, CENTER_VERTICAL, CENTER_HORIZONTAL, TOP_LEFT, TOP_CENTER, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_CENTER, BOTTOM_RIGHT
}
