data:extend({
    { label = "Door",
        id = "base.door",
        type = "structure",
        category = "structure",
        walkable = true,
        door = true,
    },
    { label = "Wood door",
        id = "base.wood_door",
        parent = "base.door",
        type = "structure",
        category = "structure",
        health = 200,
        permeability = 0.5,
        graphics = { path = "[base]/graphics/items/structures/door_wood.png", type = "door" },
        receipts = {{label = "Wood", icon = "[base]/graphics/icons/material/wood.png", components = { item = "base.consumable.wood_log", quantity = 10}}}},
    { label = "Sandstone door",
        id = "base.sandstone_door",
        parent = "base.door",
        type = "structure",
        category = "structure",
        health = 250,
        graphics = { path = "[base]/graphics/items/structures/door_wood.png", type = "door" },
        receipts = {{label = "Sandstone", icon = "[base]/graphics/icons/material/sandstone.png", components = { item = "base.sandstone_brick", quantity = 10}}}},
    { label = "Calcite door",
        id = "base.calcite_door",
        parent = "base.door",
        type = "structure",
        category = "structure",
        health = 350,
        graphics = { path = "[base]/graphics/items/structures/door_wood.png", type = "door" },
        receipts = {{label = "Calcite", icon = "[base]/graphics/icons/material/calcite.png", components = { item = "base.calcite_brick", quantity = 10}}}},
    { label = "Granite door",
        id = "base.granite_door",
        parent = "base.door",
        type = "structure",
        category = "structure",
        health = 500,
        graphics = { path = "[base]/graphics/items/structures/door_wood.png", type = "door" },
        receipts = {{label = "Granite", icon = "[base]/graphics/icons/material/granite.png"}}},
    { label = "Iron door",
        id = "base.metal_door",
        parent = "base.door",
        type = "structure",
        category = "structure",
        health = 450,
        graphics = { path = "[base]/graphics/items/structures/door_wood.png", type = "door" },
        receipts = {{label = "Iron", icon = "[base]/graphics/icons/material/iron.png", components = { item = "base.iron_plate", quantity = 10}}}},
    { label = "Carbon Fiber door",
        id = "base.carbon_fiber_door",
        parent = "base.door",
        type = "structure",
        category = "structure",
        health = 800,
        graphics = { path = "[base]/graphics/items/structures/door_wood.png", type = "door" },
        receipts = {{label = "Carbon Fiber", icon = "[base]/graphics/icons/material/carbon_fiber.png", components = { item = "base.carbon_fiber_part", quantity = 10}}}},
})
