data:extend({
    { label = "Floor",
        id = "base.floor",
        type = "structure",
        category = "structure",
        walkable = true,
    },
    { label = "Wooden floor",
        id = "base.wood_floor",
        parent = "base.floor",
        type = "structure",
        category = "structure",
        floor = { speed = 1 },
        health = 200,
        graphics = {path = "[base]/graphics/items/structures/floor_wood.png", type = "structure"},
        receipts = {label = "Wood", icon = "[base]/graphics/icons/material/wood.png", components = {{ item = "base.consumable.wood_log", quantity = 5}}}},
    { label = "Concrete floor",
        id = "base.concrete_floor",
        type = "structure",
        category = "structure",
        parent = "base.floor",
        floor = { speed = 1 },
        health = 250,
        graphics = { path = "[base]/graphics/items/structures/floor_concrete.png", type = "structure"},
        receipts = {
            {label = "Calcite", icon = "[base]/graphics/icons/material/calcite.png", components = {{ item = "base.sandstone_brick", quantity = 5}}},
            {label = "Calcite", icon = "[base]/graphics/icons/material/calcite.png", components = {{ item = "base.calcite_brick", quantity = 5}}},
            {label = "Calcite", icon = "[base]/graphics/icons/material/calcite.png", components = {{ item = "base.granite_brick", quantity = 5}}},
        }},
    { label = "Metal floor",
        id = "base.metal_floor",
        parent = "base.floor",
        type = "structure",
        category = "structure",
        floor = { speed = 1 },
        health = 250,
        graphics = {path = "[base]/graphics/items/structures/floor_metal.png", type = "structure"},
        receipts = {label = "Metal", icon = "[base]/graphics/icons/material/iron.png", components = {{ item = "base.iron_plate", quantity = 5}}}},
})
