data:extend({
    { label = "Wall",
        name = "base.wall",
        type = "structure_group",
        category = "Wall",
        is_wall = true,
        walkable = false
    },
    { label = "Wood wall",
        name = "base.wood_wall",
        parent = "base.wall",
        type = "structure",
        health = 200,
        receipts = {label = "Sandstone", icon = "[base]/graphics/icons/material/wood.png", components = { item = "base.consumable.wood_log", quantity = 10} },
        permeability = 0.2,
        graphics = {path = "[base]/graphics/items/structures/wall_wood.png", type = "wall"},
        walkable = false
    },
    { label = "Sandstone wall",
        name = "base.sandstone_wall",
        parent = "base.wall",
        type = "structure",
        health = 250,
        graphics = {path = "[base]/graphics/items/structures/wall_wood.png", type = "wall"},
        receipts = {label = "Sandstone", icon = "[base]/graphics/icons/material/sandstone.png", components = { item = "base.sandstone_brick", quantity = 10} }
    },
    { label = "Calcite wall",
        name = "base.calcite_wall",
        parent = "base.wall",
        type = "structure",
        health = 350,
        graphics = {path = "[base]/graphics/items/structures/wall_wood.png", type = "wall"},
        receipts = {label = "Calcite", icon = "[base]/graphics/icons/material/calcite.png", components = { item = "base.calcite_brick", quantity = 10} }
    },
    { label = "Granite wall",
        name = "base.granite_wall",
        parent = "base.wall",
        type = "structure",
        health = 500,
        graphics = {path = "[base]/graphics/items/structures/wall_granite.png", type = "wall"},
        receipts = {label = "Granite", icon = "[base]/graphics/icons/material/granite.png", components = { item = "base.granite_brick", quantity = 10} }
    },
    { label = "Iron wall",
        name = "base.metal_wall",
        parent = "base.wall",
        type = "structure",
        health = 450,
        graphics = {path = "[base]/graphics/items/structures/wall_wood.png", type = "wall"},
        receipts = {label = "Iron", icon = "[base]/graphics/icons/material/iron.png", components = { item = "base.iron_plate", quantity = 10} }
    },
    { label = "Carbon fiber wall",
        name = "base.carbon_fiber_wall",
        parent = "base.wall",
        type = "structure",
        health = 800,
        graphics = {path = "[base]/graphics/items/structures/wall_wood.png", type = "wall"},
        receipts = {label = "Carbon fiber", icon = "[base]/graphics/icons/material/carbon_fiber.png", components = { item = "base.carbon_fiber_part", quantity = 10} }
    },
})