data:extend({
    { label = "Military ration", name = "base.military_ration", type = "consumable", category = "food",
        consume = { cost = 20, effects = {{type = "food", quantity = 100}}},
        graphics = { path = "[base]/graphics/items/consumables/military_ration.png" },
    },
    { label = "Easy meal", name = "base.easy_meal", type = "consumable", category = "food",
        consume = { cost = 20, effects = {{type = "food", quantity = 100}}},
        graphics = { path = "[base]/graphics/items/consumables/easy_meal.png" },
    },
    { label = "Great meal", name = "base.great_meal", type = "consumable", category = "food",
        consume = { cost = 20, effects = {{type = "food", quantity = 100}}},
        graphics = { path = "[base]/graphics/items/consumables/great_meal.png" },
    },
    { label = "Lavish meal", name = "base.lavish_meal", type = "consumable", category = "food",
        consume = { cost = 20, effects = {{type = "food", quantity = 100}}},
        graphics = { path = "[base]/graphics/items/consumables/lavish_meal.png" },
    },
    { label = "Lavish seafood meal", name = "base.lavish_seafood_meal", type = "consumable", category = "food",
        consume = { cost = 20, effects = {{type = "food", quantity = 100}}},
        graphics = { path = "[base]/graphics/items/consumables/lavish_seafood_meal.png" },
    },
    { label = "Military meal", name = "base.military_meal", type = "consumable", category = "food",
        consume = { cost = 20, effects = {{type = "food", quantity = 100}}},
        graphics = { path = "[base]/graphics/items/consumables/military_meal.png" },
    },
})