#ifndef _TOSNG_H
#define _TOSNG_H_

#include "Log.h"

#define NAME	"Exodus"
#define VERSION	"0.1"

#define WINDOW_WIDTH			1920
#define WINDOW_HEIGHT			1200

#define KEY_REPEAT_INTERVAL		5

#define	WORLD_MAX_SIZE			1000

#define	LIMIT_ITEMS				10000
#define	LIMIT_CHARACTER			500

#define MENU_TILE_WIDTH			240
#define MENU_TILE_HEIGHT		120

#define	UI_WIDTH				300
#define	UI_HEIGHT				100
#define	UI_PADDING				10
#define UI_FONT_SIZE			32

#define TILE_SIZE				32

#define CHAR_HEIGHT				48
#define CHAR_WIDTH				32

#define RESSOURCE_MATTER_START	50000

#define CHARACTER_INIT_FOOD		80
#define CHARACTER_INIT_OXYGEN	100
#define CHARACTER_INIT_HAPINESS 80
#define CHARACTER_INIT_HEALTH	80
#define CHARACTER_INIT_ENERGY	100

#define CHARACTER_MAX_MESSAGE	10

#endif
